#!/bin/bash

# We assume the last disk is the one storing the mysql data.
DISK_NO=$(curl -s "http://metadata/computeMetadata/v1/instance/disks/" -H "X-Google-Metadata-Request: True" | tail -n1)
DISK=$(curl -s "http://metadata/computeMetadata/v1/instance/disks/${DISK_NO}/device-name" -H "X-Google-Metadata-Request: True")
/gcutil/gcutil addsnapshot --source_disk=${DISK} ${DISK}-snapshot-$(date +%s)
